language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade setuptools tox tox-travis python-coveralls
script:
  - tox
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coveralls --config_file=py2-coveragerc; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then coveralls --config_file=py3-coveragerc; fi
